# Generated by Django 2.2 on 2020-10-22 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('author', models.CharField(max_length=100, verbose_name='Автор цитаты')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модерированая')], default='new', max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
    ]
