# Generated by Django 2.2 on 2020-10-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20201022_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модерированная')], default='new', max_length=100, verbose_name='Статус'),
        ),
    ]
